name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read
  checks: write

jobs:
  build:
    env:
      FOURSQUARE_API_KEY: ${{secrets.FOURSQUARE_API_KEY}}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Lint checks
      run: ./gradlew :app:lint -i
    - name: Upload lint reports (HTML)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: 'app/reports/lint'
    - name: Unit tests
      run: ./gradlew testDebugUnitTest
    - name: Junit Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: JUnit Tests
        path: app/build/test-results/testDebugUnitTest/TEST-*.xml
        reporter: java-junit
        fail-on-error: false
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Android tests
      run: ./gradlew :app:Pixel_CDebugAndroidTest --stacktrace
    - name: Android Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Android Tests
        path: app/build/outputs/androidTest-results/managedDevice/debug/**/TEST-*.xml
        reporter: java-junit
        fail-on-error: false
    - name: Assemble debug
      run: ./gradlew :app:assembleDebug
    - name: Upload debug apk
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: 'app/build/outputs/apk/debug/app-debug.apk'
