name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read
  checks: write

jobs:
  build:
    env:
      FOURSQUARE_API_KEY: ${{secrets.FOURSQUARE_API_KEY}}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
# Checks
    - name: Lint checks
      run: ./gradlew :app:lint
    - name: Upload lint reports (HTML)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: 'app/reports/lint'
# Junit tests
    - name: Unit tests
      run: ./gradlew :app:testDebugUnitTest
    - name: Junit Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: JUnit Tests
        path: app/build/test-results/testDebugUnitTest/TEST-*.xml
        reporter: java-junit
        fail-on-error: false
    - name: Kover html report
      run: ./gradlew :app:koverHtmlReportDebug
    - name: Upload kover html report
      uses: actions/upload-artifact@v4
      with:
        name: kover-html-report
        path: 'app/build/reports/kover/htmlDebug'
    - name: Kover xml report
      run: ./gradlew :app:koverXmlReportDebug
    - name: Add coverage report to PR
      id: kover
      uses: mi-kas/kover-report@v1
      with:
        path: |
          ${{ github.workspace }}/app/build/reports/kover/reportDebug.xml
        title: Code Coverage
        update-comment: true
# Big(e2e) tests
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Android Pixel 2 api30 Setup
      run: ./gradlew :bigtests:pixel2api30Setup --stacktrace
    - name: Big(e2e) tests
      run: ./gradlew :bigtests:pixel2api30DebugAndroidTest --stacktrace
    - name: Android Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Android Tests
        path: bigtests/build/outputs/androidTest-results/managedDevice/debug/**/TEST-*.xml
        reporter: java-junit
        fail-on-error: false
# Build and upload
    - name: Assemble debug
      run: ./gradlew :app:assembleDebug
    - name: Upload debug apk
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: 'app/build/outputs/apk/debug/app-debug.apk'
